app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::post('admin/reserva/store2',['as'=>'admin.reserva.store2', 'uses'=>'ReservaController@store2']);
Route::get('admin/desreserva/{hora_inicio}/{fecha}/{id_clase}/{uri_anterior}',"ReservaController@desreserva_clase");
Route::get('admin/reserva/{aula}/{hora_inicio}/{fecha}/{uri_anterior}',"ReservaController@reserva_clase");
Route::get('admin/peticion/{fecha}',"PeticionController@irAHorario");
Route::get('admin/peticion/{fecha}/{id_clase}',"PeticionController@eliminarPeticion");
Route::get('admin',"DatasheetController@index");
Route::get('admin/datasheet/{tipo_mostrar?}/{dia_semana?}/{no_sala?}/{no_semana?}',"DatasheetController@index");
Route::get('/',"FrontController@index");
Route::get('admin/algoritmo/make_algoritmo','AlgoritmoController@algorithm_operation');
Route::get('admin/opciones/deleteAsignacion','OpcionesGeneralesController@deleteAsignacion');
Route::get('admin/opciones/deleteDatasheet','OpcionesGeneralesController@deleteDatasheet');

Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
Route::get('admin/clase/{clase}/createocurrence',['as'=>'admin.clase.createocurrence', 'uses'=>'ClaseController@createOcurrence']);
Route::post('admin/clase/createocurrence',['as'=>'admin.clase.storeocurrence', 'uses'=>'ClaseController@storeOcurrence']);
Route::get('admin/clase/{clase}/desvinculardocente',['as'=>'admin.clase.desvinculardocente', 'uses'=>'ClaseController@desvincularDocente']);
Route::Resource('admin/aula',"AulaController");
Route::Resource('admin/clase',"ClaseController");
Route::Resource('admin/reserva',"ReservaController");
Route::Resource('admin/perfil',"PerfilController");
Route::Resource('admin/profesores',"ProfesorController");
Route::Resource('admin/peticion',"PeticionController");
Route::get('admin/profesores/aprobar/{id}',"ProfesorController@aprobar");
Route::Resource('admin/opciones',"OpcionesGeneralesController");
Route::Resource('login',"LoginController");
Route::Resource('logout',"LoginController@logout");
Route::Resource('admin/algoritmo',"AlgoritmoController");
Route::get('admin/algoritmo/{algoritmo}/delete_aula', ['as'=>'admin.algoritmo.delete_aula', 'uses'=>'AlgoritmoController@delete_aula']);
Route::post('mobile/m_login',['as'=>'mobile.m_login', 'uses'=>'MobileController@login']);

Route::post('admin/algoritmo/algorithm_step1',['as'=>'admin.algoritmo.algorithm_step1', 'uses'=>'AlgoritmoController@algorithm_step1']);

app/Aula.php
<?php namespace Gestao;

use Illuminate\Database\Eloquent\Model;

class Aula extends Model {

protected $table ="aula";
protected $fillable = ['id','nombre','cant_equipos','cant_personas','piso'];
}

app/Http/Controllers/AulaController.php
<?php namespace Gestao\Http\Controllers;

use Gestao\Http\Requests;
use Gestao\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Gestao\Aula;
use Session;
use Redirect;
class AulaController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$aulas = aula::all();
	return view('aula.index',compact('aulas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('aula.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		try { 
		aula::create([
		'id' => $request['id'],
		'nombre' => ucwords($request['nombre']),
		'cant_equipos' => $request['cant_equipos'],
		'cant_personas' => $request['cant_personas'],
		'piso' => $request['piso'],
]);
	return redirect('admin/aula')->with('message',trans('messages.aulaCreadaCorrectamente'));
} catch(\Illuminate\Database\QueryException $ex){ return redirect('admin/aula')->with('message',trans('messages.codigoDeAulaRepetido'));   
}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$aula = aula::find($id);
		if (! $aula) {
		abort(404);
}
		return view('aula.edit',['aula'=>$aula]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$aula = aula::find($id);
		$aula -> fill($request -> all());
		$aula -> save();
		Session::flash('message',trans('messages.aulaModificada'));
		return Redirect::to('admin/aula');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		aula::destroy($id);
		Session::flash('message',trans('messages.aulaEliminada'));
		return Redirect::to('admin/aula');	
	}

}

resources/views/aula/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">	
{!!Form::open(['route'=>'admin.aula.store', 'method'=>'POST'])!!}
@include('aula.forms.aula_form')
	{!!Form::submit(trans('messages.registrar'),['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
	</div>
@stop

resources/views/aula/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">	
<div class="row">
	<ol class="breadcrumb">
		<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
		<li class="active" id="form_name" name="rol" duplicate="name">Aula / Actualizar</li>
	</ol>
</div><br>
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<center>Actualizar Aula</center>
		</div>
		<div class="panel panel-body">
				{!!Form::model($aula, ['route'=>['admin.aula.update', $aula -> id],'method'=>'PUT'])!!}
				@include('aula.forms.aula_form')
		</div>
		<div class="panel panel-footer">
			<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-2">
			<center>{!!Form::submit(trans('messages.actualizar'),['class'=>'btn btn-warning btn_actu'])!!}
			{!!Form::close()!!}</center>
			</div>
			<div class="col-md-2">
			<center><a type="button" class="btn btn-primary " href="../../../admin/aula">Cancelar</a></center>
			</div>
			</div>			
		</div>					
	</div>
</div>
			@stop

resources/views/aula/index.blade.php
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="crediavales-label" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
				<h4 class="modal-title" id="project-12-label"><center>Nuevo</center></h4>
			</div>
			<div class="modal-body">
			{!!Form::open(['route'=>'admin.aula.store', 'method'=>'POST'])!!}
				<div class="form-group">
					{!!Form::label('nombre',trans('messages.codigoDeAula'))!!}
					{!!Form::text('id',null,['class'=>'form-control','required'])!!}
				</div>
				<div class="form-group">
					{!!Form::label('nombre_aula',trans('messages.nombreDeLaAula'))!!}
					{!!Form::text('nombre',null,['class'=>'form-control','placeholder'=>trans('messages.ejemSalaI'),'required'])!!}
				</div>

				<div class="form-group">
					{!!Form::label('cant_personas',trans('messages.cantidadDePersonas'))!!}
					{!!Form::number('cant_personas',null,['class'=>'form-control','min'=>'1','max'=>'45','required'])!!}
				</div>
				<div class="form-group">
					{!!Form::label('cant_equipos',trans('messages.cantidadDeEquipos'))!!}
					{!!Form::number('cant_equipos',null,['class'=>'form-control','min'=>'1','max'=>'40','required'])!!}
				</div>
				<div class="form-group">
					{!!Form::label('aula_piso',trans('messages.piso'))!!}
					{!!Form::number('piso',null,['class'=>'form-control','min'=>'1','max'=>'2','required'])!!}
				</div>
				
				
			</div>
			<div class="modal-footer">
			<center>
			{!!Form::submit(trans('messages.registrar'),['class'=>'btn btn-success'])!!}
			<a type="button"class="btn btn-primary " data-toggle="modal">Cancelar</a>
			{!!Form::close()!!}
			</center>
			</div>

			
		</div>
	</div>
</div>

@extends('layouts.admin')
@section('content')

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
<div class="row">
	<ol class="breadcrumb">
		<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
		<li class="active" id="form_name" name="rol" duplicate="name">Aula</li>
	</ol>
</div><!--/.row-->
@if (Session::has('message'))
<br>
<div class="alert alert-success">
  {{ Session::get('message') }}
</div>
@endif
<br>
<div class="row">
<div class="col-lg-12">
	<div class="panel panel-default">
	
		<div class="panel-heading">
			<a type="button" class="btn btn-success glyphicon glyphicon-plus" data-toggle="modal"  data-target="#new"> </a>
		</div>
		
		<div class="panel panel-body">
			<table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" class="table table-hover">
				<thead>
					<tr>
						<th>{{ trans('messages.id') }}</th>
						<th>{{ trans('messages.nombre') }}</th>
						<th>{{ trans('messages.cantidadDePersonas') }}</th>
						<th>{{ trans('messages.cantidadDeEquipos') }}</th>
						<th>{{ trans('messages.piso') }}</th>
						<th >Actualizar</th>
						<th>Eliminar</th>
						
					</tr>
				</thead>
				<tbody>
				@foreach($aulas as $aula)
					<tr>
						<td>{{ $aula -> id }}</td>
						<td>{{ $aula -> nombre }}</td>
						<td>{{ $aula ->	cant_personas }}</td>
						<td>{{ $aula -> cant_equipos }}</td>
						<td>{{ $aula -> piso }}</td>
						<td>{!!link_to_route('admin.aula.edit', $title = trans('messages.editar'), $parameters = $aula->id, $attributes = ['class'=>'btn btn-warning '])!!}</td>
						<td>{!!Form::open(['route'=>['admin.aula.destroy', $aula -> id],'method'=>'DELETE']) !!}
						{!!Form::submit(trans('messages.eliminar'),['class'=>'btn btn-danger '])!!}
						{!!Form::close()!!}</td>
						
						
					</tr>				
				@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>
</div>
@stop