app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::post('admin/reserva/store2',['as'=>'admin.reserva.store2', 'uses'=>'ReservaController@store2']);
Route::get('admin/desreserva/{hora_inicio}/{fecha}/{id_clase}/{uri_anterior}',"ReservaController@desreserva_clase");
Route::get('admin/reserva/{aula}/{hora_inicio}/{fecha}/{uri_anterior}',"ReservaController@reserva_clase");
Route::get('admin/peticion/{fecha}',"PeticionController@irAHorario");
Route::get('admin/peticion/{fecha}/{id_clase}',"PeticionController@eliminarPeticion");
Route::get('admin',"DatasheetController@index");
Route::get('admin/datasheet/{tipo_mostrar?}/{dia_semana?}/{no_sala?}/{no_semana?}',"DatasheetController@index");
Route::get('/',"FrontController@index");
Route::get('admin/algoritmo/make_algoritmo','AlgoritmoController@algorithm_operation');
Route::get('admin/opciones/deleteAsignacion','OpcionesGeneralesController@deleteAsignacion');
Route::get('admin/opciones/deleteDatasheet','OpcionesGeneralesController@deleteDatasheet');

Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
Route::get('admin/clase/{clase}/createocurrence',['as'=>'admin.clase.createocurrence', 'uses'=>'ClaseController@createOcurrence']);
Route::post('admin/clase/createocurrence',['as'=>'admin.clase.storeocurrence', 'uses'=>'ClaseController@storeOcurrence']);
Route::get('admin/clase/{clase}/desvinculardocente',['as'=>'admin.clase.desvinculardocente', 'uses'=>'ClaseController@desvincularDocente']);
Route::Resource('admin/aula',"AulaController");
Route::Resource('admin/clase',"ClaseController");
Route::Resource('admin/reserva',"ReservaController");
Route::Resource('admin/perfil',"PerfilController");
Route::Resource('admin/profesores',"ProfesorController");
Route::Resource('admin/peticion',"PeticionController");
Route::get('admin/profesores/aprobar/{id}',"ProfesorController@aprobar");
Route::Resource('admin/opciones',"OpcionesGeneralesController");
Route::Resource('login',"LoginController");
Route::Resource('logout',"LoginController@logout");
Route::Resource('admin/algoritmo',"AlgoritmoController");
Route::get('admin/algoritmo/{algoritmo}/delete_aula', ['as'=>'admin.algoritmo.delete_aula', 'uses'=>'AlgoritmoController@delete_aula']);
Route::post('mobile/m_login',['as'=>'mobile.m_login', 'uses'=>'MobileController@login']);

Route::post('admin/algoritmo/algorithm_step1',['as'=>'admin.algoritmo.algorithm_step1', 'uses'=>'AlgoritmoController@algorithm_step1']);

app/Clase.php
<?php

namespace Gestao;

use Illuminate\Database\Eloquent\Model;

class Clase extends Model
{
    protected $table ="clase";
	protected $fillable = ['id','nombre','grupo','creditos','semestre','cant_estudiantes','requerimientos'];
}

app/Http/Controllers/ClaseController.php
<?php

namespace Gestao\Http\Controllers;

use Illuminate\Http\Request;

use Gestao\Http\Requests;
use Gestao\Http\Controllers\Controller;
use Gestao\Clase;
use Gestao\ClaseAulaHorario;
use Gestao\Constante;
use Session;
use Redirect;
use DB;

class ClaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    $clases = DB::table('clase')
            ->leftJoin('persona', 'persona.id', '=', 'clase.id_docente')->select('clase.id','nombre','grupo','creditos','semestre','cant_estudiantes','requerimientos',DB::raw('CONCAT(nombre1," " , apellido1) As docente'))->get();
    return view('clase.index',compact('clases'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clase.create');
    }

    public function createOcurrence($id){
        return view('clase.create_ocurrence',['clase'=>$id]);
    }

    public function desvincularDocente($id){
        $clase = clase::find($id);
        $clase['id_docente'] = null;
        $clase -> save();
        Session::flash('message',trans('messages.docenteDesvinculado'));
        return Redirect::to('admin/clase');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

try { 
  clase::create([
        'id' => $request['id'],
        'nombre' => ucwords($request['nombre']),
        'grupo' => $request['grupo'],
        'creditos' => $request['creditos'],
        'semestre' => $request['semestre'],
        'cant_estudiantes' => $request['cant_estudiantes'],
        'requerimientos' => $request['requerimientos'],
]);
       
       $this->calculateStoreOcurrence($request);

    return redirect('admin/clase')->with('message',trans('messages.claseCreadaCorrectamente'));   
} catch(\Illuminate\Database\QueryException $ex){ 
 return redirect('admin/clase')->with('message',trans('messages.codigoDeClaseRepetido'));   
}

      
        
    }

    public function storeOcurrence(Request $request){
        $this->calculateStoreOcurrence($request);
        return redirect('admin/clase')->with('message',trans('messages.ocurrenciaCreadaCorrectamente'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clase = clase::find($id);
       
        return view('clase.edit',['clase'=>$clase]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $clase = clase::find($id);
        $clase -> fill($request -> all());
        $clase -> save();
        Session::flash('message',trans('messages.claseModificada'));
        return Redirect::to('admin/clase');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        clase::destroy($id);
        Session::flash('message',trans('messages.claseEliminada'));
        return Redirect::to('admin/clase');  
    }

    public function calculateStoreOcurrence($request){
         $finalSemestre = Constante::where('id','=','FINSEM')->first();
        $diaSemanaActual= ((getDate(time())['wday'])+6)%7;
        if($diaSemanaActual == $request['dia']){
            if($request['horaInicio']<= getDate(time())['hours']){
                $request['dia'] = $request['dia'] + 7;
            }

        }
        elseif($request['dia'] < $diaSemanaActual){
            $request['dia'] = $request['dia'] + 7;
        }
        $difDias= $request['dia'] - $diaSemanaActual ;
        $fechaEnHorario =strtotime("+".$difDias." day", time());

        $fechaInicial = date_create(date("Y-m-d H:i:s", $fechaEnHorario));
        $fechaFinal = date_create(date("Y-m-d H:i:s", $fechaEnHorario));

        date_time_set($fechaInicial, $request['horaInicio'], 0);
        date_time_set($fechaFinal, $request['horaFinal'], 0);

        $fechaInicial= $fechaInicial->getTimestamp();
        $fechaFinal= $fechaFinal->getTimestamp();
        $finalSemestre=strtotime($finalSemestre->valor);
        
        if($request['ocurrencias']==0){
            while($fechaInicial < $finalSemestre){
                DB::table('clase_aula_horario')->insert(
                    array('id_clase' => $request['id'],
                         'hora_inicio' =>  getDate($fechaInicial)['hours'] ,
                         'hora_final'=> getDate($fechaFinal)['hours'],
                         'fecha'=> date("Y-m-d", $fechaInicial) )
                );
                $fechaInicial = strtotime("+7 day",$fechaInicial);  
            }
        }else{
            DB::table('clase_aula_horario')->insert(
                array('id_clase' => $request['id'],
                    'hora_inicio' =>  getDate($fechaInicial)['hours'] ,
                    'hora_final'=> getDate($fechaFinal)['hours'],
                    'fecha'=> date("Y-m-d", $fechaInicial) )
            );

        }
    }
}

resources/views/clase/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">	
{!!Form::open(['route'=>'admin.clase.store', 'method'=>'POST'])!!}
@include('clase.forms.clase_form')
@include('clase.forms.clase_ocurrencia_form')
	{!!Form::submit(trans('messages.registrar'),['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
	</div>
@stop

resources/views/clase/create_ocurrence.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">	
<div class="row">
	<ol class="breadcrumb">
		<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
		<li class="active" id="form_name" name="rol" duplicate="name">Clase / Añadir Ocurrencia</li>
	</ol>
</div><br>
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<center>Añadir Ocurrencia</center>
		</div>
		<div class="panel panel-body">
		{!!Form::open(['route'=>'admin.clase.storeocurrence', 'method'=>'POST'])!!}
		{!! Form::hidden('id', $clase) !!}
		@include('clase.forms.clase_ocurrencia_form')
		</div>
		<div class="panel panel-footer">
			<center>{!!Form::submit(trans('messages.registrar'),['class'=>'btn btn-success btnocu'])!!}</center>
		{!!Form::close()!!}
		</div>
		
	</div>
@stop

resources/views/clase/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">	
<div class="row">
	<ol class="breadcrumb">
		<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
		<li class="active" id="form_name" name="rol" duplicate="name">Clase / Actualizar</li>
	</ol>
</div><br>
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<center>Actualizar Clase</center>
		</div>
		<div class="panel panel-body">
		{!!Form::model($clase, ['route'=>['admin.clase.update', $clase -> id],'method'=>'PUT'])!!}
		@include('clase.forms.clase_form')
		</div>
		<div class="panel panel-footer">
			<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-2">
			<center>{!!Form::submit(trans('messages.actualizar'),['class'=>'btn btn-warning'])!!}
			{!!Form::close()!!}</center>
			</div>
			<div class="col-md-2">
			<center>{!!Form::open(['route'=>['admin.clase.destroy', $clase -> id],'method'=>'DELETE']) !!}
			{!!Form::submit(trans('messages.eliminar'),['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}</center>
			</div>
			</div>			
		</div>	
	</div>
@stop

resources/views/clase/index.blade.php
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="crediavales-label" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
				<h4 class="modal-title" id="project-12-label"><center>Nuevo</center></h4>
			</div>
			<div class="modal-body">
				{!!Form::open(['route'=>'admin.clase.store', 'method'=>'POST'])!!}
				<div class="row">
				<div id='clase_error_div'>
<div class="alert alert-warning">
  					<strong>{!!Form::label('errors_clase','')!!}</strong> 
					</div>
					</div>
					<div class="col-md-6">
						<div class="col-md-6">
							{!!Form::label('id',trans('messages.codigoDeLaClase'))!!}
							{!!Form::text('id',null,['class'=>'form-control','required'])!!}
						</div>
						<div class="col-md-6">
							{!!Form::label('nombre_aula',trans('messages.nombreDeLaClase'))!!}
							{!!Form::text('nombre',null,['class'=>'form-control','placeholder'=>trans('messages.ejemComputacionGrafica'),'required'])!!}
						</div>
						<div class="form-group">
							{!!Form::label('grupo',trans('messages.grupo'))!!}
							{!!Form::text('grupo',null,['class'=>'form-control','placeholder'=>trans('messages.ejemSis501')])!!}
						</div>
						
						<div class="form-group">
							{!!Form::label('creditos',trans('messages.numeroDeCreditos'))!!}
							{!!Form::number('creditos',null,['class'=>'form-control','min'=>'1','max'=>'5'])!!}
						</div>
						<div class="form-group">
							{!!Form::label('semestre',trans('messages.semestre'))!!}
							{!!Form::number('semestre',null,['class'=>'form-control','min'=>'1','max'=>'12'])!!}
						</div>
						<div class="form-group">
							<center>{!!Form::label('cant_estudiantes',trans('messages.cantidadDeEstudiantes'))!!}</center>
							{!!Form::number('cant_estudiantes',null,['class'=>'form-control','min'=>'1','required'])!!}
						</div>
						<div class="form-group">
							{!!Form::label('requerimientos',trans('messages.requerimientos'))!!}
							{!!Form::text('requerimientos',null,['class'=>'form-control'])!!}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
					    	{!!Form::label('horario',trans('messages.horario'))  !!}
					    </div>
					    <div class="form-group">
					    	{!!Form::label('dia',trans('messages.diaDeLaSemana'))!!}
					    	{!! Form::select('dia', [trans('messages.lunes'), trans('messages.martes'),trans('messages.miercoles'),trans('messages.jueves'),trans('messages.viernes'),trans('messages.sabado')]) !!}
					    </div>
					    <div class="form-group">
					    	{!!Form::label('horaInicio',trans('messages.horaInicial'))!!}
					    	{!!Form::number('horaInicio',null,['class'=>'form-control clase_hora_inicio','min'=>'7','max'=>'21','required'])!!}
					    </div>
					    <div class="form-group">	
					    	{!!Form::label('horaFinal',trans('messages.horaFinal'))!!}
					    	{!!Form::number('horaFinal',null,['class'=>'form-control clase_hora_final','min'=>'8','max'=>'22','required'])!!}
					    </div>
					    <div class="form-group">
					    {!!Form::label('ocurrencias',trans('messages.ocurrencias'))!!}
					    {!! Form::select('ocurrencias', [trans('messages.todoElSemestre'), trans('messages.unaSolaVes')]) !!}
					    </div>	
					</div>
				</div>
			</div>
			<div class="modal-footer">
			<center>
			{!!Form::submit(trans('messages.registrar'),['class'=>'btn btn-success btn_create_class'])!!}
			<a type="button"class="btn btn-primary " data-toggle="modal">Cancelar</a>
			{!!Form::close()!!}
			</center>
			</div>			
		</div>
	</div>
</div>
@extends('layouts.admin')
@section('content')
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
<div class="row">
	<ol class="breadcrumb">
		<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
		<li class="active" id="form_name" name="rol" duplicate="name">Clase</li>
	</ol>
</div><br>	
@if (Session::has('message'))
	<div class="alert alert-success">
  	{{ Session::get('message') }}
	</div>
@endif
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<a type="button" class="btn btn-success glyphicon glyphicon-plus" data-toggle="modal"  data-target="#new"> </a>
			</div>
			<div class="panel panel-body">
				<table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" class="table table-hover">
					<thead>
						
							<th>{{ trans('messages.id') }}</th>
							<th>{{ trans('messages.nombre') }}</th>
							<th>{{ trans('messages.grupo') }}</th>
							<th>{{ trans('messages.creditos') }}</th>
							<th>{{ trans('messages.semestre') }}</th>
							<th>{{ trans('messages.cantidadDeEstudiantes') }}</th>
							<th>{{ trans('messages.docente') }}</th>
							<th>{{ trans('messages.requerimientos') }}</th>
							<th>{{ trans('messages.editar') }}</th>
							<th>{{ trans('messages.eliminar') }}</th>
							<th>{{ trans('messages.desvincularDocente') }}</th>
						
					</thead>
					<tbody>
					@foreach($clases as $clase)
						<tr>
							<td>{{ $clase -> id }}</td>
							<td>{{ $clase -> nombre }}</td>
							<td>{{ $clase -> grupo }}</td>
							<td>{{ $clase -> creditos }}</td>
							<td>{{ $clase -> semestre }}</td>
							<td>{{ $clase -> cant_estudiantes }}</td>
							<td>{{ $clase -> docente }}</td>
							<td>{{ $clase -> requerimientos }}</td>
							<td>{!!link_to_route('admin.clase.edit', $title = trans('messages.editar'), $parameters = $clase->id, $attributes = ['class'=>'btn btn-warning'])!!}
							</td>
							<td>{!!link_to_route('admin.clase.createocurrence', $title = trans('messages.anadirOcurrencia'), $parameters = $clase->id, $attributes = ['class'=>'btn btn-primary'])!!}
							</td>
							<td>{!!link_to_route('admin.clase.desvinculardocente', $title = trans('messages.desvincularDocente'), $parameters = $clase->id, $attributes = ['class'=>'btn btn-danger'])!!}
							</td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>

</div>
@stop